# Make sure to check the documentation at http://goreleaser.com
project_name: opg-ecs-helper

release:
  github:
    owner: ministryofjustice
    name: opg-ecs-helper

builds:
  - binary: ecs-runner
    id: ecs-runner
    main: ./cmd/runner/main.go
    goarch:
      - amd64
  - binary: ecs-stabilizer
    id: ecs-stabilizer
    main: ./cmd/stabilizer/main.go
    goarch:
      - amd64

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
